### ISSUE TITLE
Flash night

### ISSUE THREAD

**Issue by noxilixon** [freifunk-berlin/meta#108]
We have a lot of devices in the FF-Room that need to be set to default OpenWRT. Let's do it together in a long session.

_See minutes Community-Day [22.9.24](https://github.com/freifunk-berlin/meta/blob/main/protokolle/2024-09-22.md)_

**Comment by noxilixon** [comment]
And lets watch some halloween movies XD

**Comment by pktpls** [comment]
Going to be fun :monkey:

**Comment by nicolasberens** [comment]
yes, (since i proposed it)

30th is fine by me.

I can take care of all the fritz! devices

**Comment by Noki** [comment]
30th it is...
