### ISSUE TITLE
Hardware recommendation

### ISSUE THREAD

**Issue by noxilixon** [freifunk-berlin/meta#111]
It is often asked about hardware recommendations. There is an [old version in the wiki](https://wiki.freifunk.net/Berlin:Firmware#Unterst.C3.BCtzte_Router). We should update this and think about a good process for this in the future.

_See minutes Community-Day [22.9.24](https://github.com/freifunk-berlin/meta/blob/main/protokolle/2024-09-22.md)_

**Comment by adam-burns** [comment]
> _See minutes Community-Day [22.9.24](https://github.com/freifunk-berlin/meta/blob/main/protokolle/2024-09-22.md)_

link to minutes 404's :disappointed:

**Comment by Noki** [comment]
I changed the recommendations to some more modern devices we often use and by adding a link to the list of Wi-Fi 6 devices supported by OpenWRT as general guideline.
