### ISSUE TITLE
Hackday

### ISSUE THREAD

**Issue by noxilixon** [freifunk-berlin/meta#16]
We want to do a hackathon on a Sunday in November. The Idea was to have a mentor-person to a certain topic and other freifunkas could join this working group during the day to reach the goal of the day.

**Comment by FFHener** [comment]
I reserved the room at Kirchhofstr for the 19th of November

**Comment by noxilixon** [comment]
Brainstorming zu Aufgaben die für das gemeinsame Ziel nötig oder hilfreich sind. Soll dann noch in Issues umgewandelt werden:

- [add submodule for external dependency](https://github.com/freifunk-berlin/falter-packages/pull/390) testen und mergen
- Olsrd Luci Plugin updaten
- ucode scripts für ff spezifische ubus calls
- Firewall regeln aktualisieren
- Tests schreiben / aktualisieren / automatisieren
- Luci durchtesten
- Luci login issue lösen

**Comment by FFHener** [comment]
Der Tag hat stattgefunden und war gut besucht. Die angestrebten Punkte hier aus dem Issue waren nicht komplett der Fokus, sondern es wurden teils auch andere liegen gebliebene Probleme gelöst
