### ISSUE TITLE
uisp.olsr: Migration to community owned infrastructure

### ISSUE THREAD

**Issue by FFHener** [freifunk-berlin/meta#19]
TODOs:

- [x] install uisp auf 10.31.130.158
- [x] update ak36-gw so das uisp.olsr auf 10.31.130.158 geht
- [x] update alte router der uisp genoucnet hat so das es nicht mehr macht
- [x] add users (@Noki,... ) auf system die den sysadmin machen wollen 
- [x] Transfer UISP setup from alte server auf neue server.

**Comment by pmelange** [comment]
Hey, you forgot ToDo number 6 :)

![Screenshot_2023-11-21_15-36-18](https://github.com/freifunk-berlin/meta/assets/20710446/c42fdd4c-0899-4e4c-8a55-e2b0cb2b414c)

**Comment by Noki** [comment]
@pmelange I stubled accross the official requirements for UISP: https://help.ui.com/hc/en-us/articles/115012196527-UISP-First-Time-Setup-Installation

Can you please increase the memory for the VM to 4 GB?!?

**Comment by pmelange** [comment]
> @pmelange I stubled accross the official requirements for UISP: https://help.ui.com/hc/en-us/articles/115012196527-UISP-First-Time-Setup-Installation
> 
> Can you please increase the memory for the VM to 4 GB?!?

Done.  Please reboot the VM to make the changes take affect.

**Comment by Noki** [comment]
@pmelange I rebooted the machine, however no change...

![image](https://github.com/freifunk-berlin/meta/assets/198902/bf521bff-1e5a-4f77-895d-c812e731ed93)

**Comment by pmelange** [comment]
> @pmelange I rebooted the machine, however no change...
> 
> ![image](https://user-images.githubusercontent.com/198902/285191165-bf521bff-1e5a-4f77-895d-c812e731ed93.png)

Fixed, and restarted

**Comment by FFHener** [comment]
@Noki is this issue done?

**Comment by Noki** [comment]
Yes!
