### ISSUE TITLE
Mela: New core router + AC Hardware for Teufelsberg Uplink

### ISSUE THREAD

**Issue by Noki** [freifunk-berlin/meta#22]
**Contact:**
Noki
torte_ff
https://matrix.to/#/!siDSiHHFwuenlxnrGR:matrix.org?via=matrix.org

**Location:**
Melanchthon Kirche Berlin-Spandau - https://wiki.freifunk.net/Berlin:Standorte:Melanchthon_Gemeinde_Berlin-Spandau

**Use:**
For the site, with the intention to connect the site to the backbone via Teufelsberg and to slightly modernize it.

**Devices List:**
Fritzbox 4040 - 83,99 EUR - https://www.cosse.de/pc-multimedia/netzwerk-komponenten/wireless-lan/15013/avm-fritz-box-4040?etcc_cmp=Idealo&etcc_med=Preisvergleich&etcc_par=&etcc_ctv=606732
Ubiquiti NanoBeam AC GEN2 - NBE-5AC-Gen2 - 94,88 EUR - https://direkt.jacob.de/produkte/ubiquiti-nanobeam-m5-nbe-5ac-gen2-artnr-3665595.html?ref=109&utm_campaign=Preisvergleich&utm_medium=cpc&utm_source=idealo

**Total cost:**
178,87 EUR

(See [instructions](https://github.com/freifunk-berlin/meta/blob/main/Hardware-orders.md))

**Comment by noxilixon** [comment]
We did not specify this in the guideline, but a upvote for the own issue does obviously not count XDD

**Comment by PolynomialDivision** [comment]
A FritzBox 4040 for such an important location?

**Comment by Noki** [comment]
A location where we currently do not even have access to, all hardware is very old, and with no bbb connection... The idea is to replace the core-router that is stuck in a boot loop, upgrade the software side to a current state, allow people to mesh via 802.11s and connect it to Teufelsberg. After that we can upgrade it once we have an idea what actually makes sense...

**Comment by nicolasberens** [comment]
FYI: We still have a few 7530 that we can use.
