### ISSUE TITLE
Rocket AC Lite and Titanium Sector Antena for Philmel

### ISSUE THREAD

**Issue by Petrella** [freifunk-berlin/meta#24]
**Contact:**
@roedel:matrix.org

**Location:**
- philmel / Phillipp-Melancthon Kirche, Kranoldstraße

**Use:**
- Use is for the site and its peers and also for the whole network
- The sectorial Antena with radio will be used to cover the east direction of the tower. Existing Peers will be connected via AC. 
- Also a link between Vaterhaus and Philmel should be re-established with chris-gueffroy in the middle. 
- The link between philmel <-> vaterhaus was removed due to buildings and constructions which blocked the line of sight permanently
- It is also part in the reneval of the philmel site. There's already this combination of Hardware facing into other directions on the tower

**Devices List:**
- airMAX Rocket AC Lite [airMAX Rocket AC Lite](https://www.getic.com/product/rocket-ac-lite) (~122€)
- [Ubiquiti Airmax Sector Titanium - AM-M-V5G-Ti
](https://www.omg.de/ubiquiti-networks/antennen/sektor-antennen/ubiquiti-titanium-sektor-antenne-5-ghz-60-120-15-17db-fuer-rocket-m5-titanium/a-13360#product-technical-data) (~166€)
- Some material for mounting (~12€)

**Total cost:**
- about 300 euros

**Comment by Noki** [comment]
The connection would be really good for the network as it adds redundancy.

**Comment by noxilixon** [comment]
Final costs were: 317.37€
