### ISSUE TITLE
Power Beam 500AC ISO for PtmP chris-gueffroy <-> philmel

### ISSUE THREAD

**Issue by Petrella** [freifunk-berlin/meta#25]
**Contact:**
@roedl:matrix.org

**Location:**
- chris-gueffroy (Treptow/Köpenick, Baumschulenweg)

**Use:**
- For the site and the entire Network
- It should be used to reastablish the connection between vaterhaus <-> philmel via chris-gueffroy
- The direct LoS between vaterhaus and philmel was blocked permanently through construction work and buildings

**Devices List:**
- [Power Beam 500 ac](https://www.omg.de/ubiquiti-networks/airmax/powerbeam/pbe-5ac-iso-gen2/a-14649)

**Total cost:**
- about 136€

**Comment by Noki** [comment]
This would be very good for the network.

**Comment by noxilixon** [comment]
Final costs were:  132.55€
