### ISSUE TITLE
NetPower 16P for Philmel

### ISSUE THREAD

**Issue by Petrella** [freifunk-berlin/meta#26]
**Contact:**
@roedel:matrix.org

**Location:**
- Philmel/Phillip Melanchton Kirche

**Use:**
- will be used on the location for switching and PoE
- will be used for the entire Network as the location is part of the southern border of the ff-ring around the city
- will be used for the entire Network because the PtP connections on philmel to other locations can be used as redundancy
- Usage as a replacement for the two Edgerouter X SFP which are only used as switches right now
- One Device for switching is preferred

**Devices List:**
- [Switch Netpower 16P](https://www.omg.de/mikrotik/cloud-router-switches/cloud-router-switches/mikrotik-netpower-16p/a-22549)
- [Power Supply for 24V PoE](https://www.omg.de/mikrotik/mikrotik-24hpow-24v-netzteil-24v-1-2a/a-13882)
- [Power Supply for 48V PoE](https://www.omg.de/mikrotik/zubehoer/adapter/mikrotik-48v-2a-96w-netzteil-48v2a96w/a-14723)
**Total cost:**
- around 300€

**Comment by booo** [comment]
Is that the new standard switch we would like to use? Especially with the switches I would love to have a similar setup at each location.

**Comment by Petrella** [comment]
The Switch is used at AK36 right now. It has many advantages compared to other PoE switches: 
- It's an outdoor switch and is solid and rugged
- It has PoE 48v & 24v passive and all other important standards
- It has no Fan
- It has SFP+ for future expansions
- It has enough ports for a middle size to big location

**Comment by noxilixon** [comment]
Final costs were: 301.32€
