### ISSUE TITLE
scharni38: 60 ghz wave nano link to samariter

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/meta#28]
**Contact:**
#scharni38:matrix.riotcat.org

**Location:**
Scharni38

**Use:**
Samariter church now has a 60 Ghz antenna for clients that want to connect on the south window. The Scharni is used as a distribution centre for its neighbors (e.g. colbe-core) to connect to the network and also contains event rooms that are equipped with freifunk. Maybe Scharni will also become new gateway in future when we get a sponsorship from versatel. The 5GHz connection to Samariter is suffering from noise and bad signal. Already all traffic is routed through zwingli. It would be nice to get a direct 60 GHz connection to Samariter for that important freifunk site.

**Devices List:**
Ubiquiti UISP Wave Nano

**Total cost:**
210,52€

**Comment by PolynomialDivision** [comment]
ping @noxilixon ;)

**Comment by FFHener** [comment]
This Request will likely be dealt with on Tuesday

**Comment by noxilixon** [comment]
Final costs were: 226.68€
