### ISSUE TITLE
suedblock: offline

### ISSUE THREAD

**Issue by FFHener** [freifunk-berlin/meta#41]
Ist immer mal wieder offline da auf dem Gerät noch immer Tunnelmanager läuft und das Gerät nicht mit Tunspace neu geflashed werden kann. Ein Austauschgerät liegt schon bei @pktpls und muss nur vor Ort installiert werden.

**Comment by Noki** [comment]
This was resolved by https://github.com/freifunk-berlin/bbb-configs/pull/938
