### ISSUE TITLE
kiehlufer: fix rocket

### ISSUE THREAD

**Issue by Noki** [freifunk-berlin/meta#46]
- [x] flash
- [x] replace kiehlufer-huette

Die Antenne kiehlufer-huette ist in einem Zustand, wo sich diese nicht mehr von extern mit neuerer Firmware flashen lässt (OpenWRT Bug, der inzwischen gefixt wurde). Die bestehende Firmware hat Probleme ein stabiles Mesh zu erzeugen, wodurch die Mesh-Nachbarn immer wieder offline gehen. Die Antenne müsste über TFTP neu geflashed werden oder durch eine andere, bereits geflashte getauscht werden.

**Comment by Noki** [comment]
I think it was replaced and the issue could be closed, right?

**Comment by Koltonowski** [comment]
rocket was replaced and flashed. Issue closed.
