### ISSUE TITLE
Please turn off freifunk.net in Baumschulenweg

### ISSUE THREAD

**Issue by zenhund74** [freifunk-berlin/meta#47]
Dear freifunk.net community

I live in Baumschulenweg, 12437 Berlin and the freifunk.net doesn`t seem to be functional anymore.
But also, due to it`s elevated strength it competes with normal wifi signals in our house.

I was an absolute fan of this initiative 20 years ago, but I believe it is pretty outdated by now.

Could you just turn it off?

Kind regards, Jens.

**Comment by kls0e** [comment]
There is a larger mesh directly at S Plänterwald, in the KGA am Heidekampgraben e.V.. Some of the nodes can be flaky, but overall the mesh is used actively and regularly. In case this is relevant, here are Info & contact: https://kga-am-heidekampgraben.de/freifunk/

**Comment by xa-y-ax** [comment]
Wenn @zenhund74 nicht mehr reagiert, können wir vielleicht das Issue schließen? Ich sehe zumindest keine Ausfälle bei den mir bekannten Nodes...

**Comment by Noki** [comment]
feel free to reopen with more information at any time...
