### ISSUE TITLE
Communitysamstag 16.9.

### ISSUE THREAD

**Issue by pktpls** [freifunk-berlin/meta#5]
Hier auch nochmal die Einladung zum Communitysamstag am 16.9., die schon über die Mailingliste ging https://lists.berlin.freifunk.net/pipermail/berlin/2023-August/053474.html

Wann: Samstag 16.9. 11:00
Wo: Büro Kirchhofstr. 45 (nahe S-Bhf Neukölln)

Vorschlag Ablauf:
- 11:00 BYOB Bring your own Brunch
  - https://pad.freifunk.net/p/16.9.Brunch
  - bitte auch Allergien und Präferenzen eintragen, auch wegen Abendessen :)
- 13:00 Start
- kurze Pause
- 14:00 Thema 1
  - Vorschlag: Routing https://github.com/freifunk-berlin/meta/issues/3
- Pause
- 16:30 Thema 2
  - Vorschlag: Firmware https://github.com/freifunk-berlin/meta/issues/4
- Pause
- Abendessen, danach Rumhängen, Vorträge, Hacking, Film, etc.

Es gibt zwei ausreichend große Räume um sich auch mal rauszuziehen oder zwei Sachen parallel zu machen. Ich glaube es wird ein netter Tag und vielleicht machen wir ja noch ein weiteres Mal in den nächsten Monaten :smile:

**Comment by noxilixon** [comment]
# Detaillierter Ablauf mit Zuständigkeiten:

**Gemeinsamer Start:**
- Warum gibt es diesen Tag (Lars)
- Rahmen vom Tag (Lino)
- Programm vorstellen (Lino)
- Umgang mit Themen für die wir keine Zeit haben (Lino)
- Vorstellungsrunde (Hener)
- Erwartungen abfragen (Hener)

**Firmware** (Akira?)

**Routing** (Lars)

**Comment by noxilixon** [comment]
Präsentationen für den Abend:

- Wiki Updater
- Camp Setup
- Hardware Vergabe
- Buildbot
- Teufelsberg Ausbau
- Ucode

**Comment by PolynomialDivision** [comment]
What about T-Shirts? ;)

**Comment by pktpls** [comment]
Yes, please wear a T-Shirt :-)

**Comment by noxilixon** [comment]
Protokoll: [protokolle/2023-09-16.md](https://github.com/freifunk-berlin/meta/blob/main/protokolle/2023-09-16.md)
