### ISSUE TITLE
Untermiete mit Searchwing klären

### ISSUE THREAD

**Issue by noxilixon** [freifunk-berlin/meta#55]
Wenn HdM umzieht wollen wir nicht nochmal Hauptmieter werden. Aber wenn mögflich würden wir gerne Untermieter bei Searchwing werden. Das müsste aucgecheckt werden.

**Comment by FFHener** [comment]
Iirc ging es dabei mehr um eine strukturelle Frage als eine rechtliche, also nicht wer nachher im Mietvertrag steht, sondern dass wir uns vorstellen könnten einen hauptsächlich von Search Wing genutzten Raum auch ab und zu zu verwenden und ein Regal zum lagern stehen zu haben
