### ISSUE TITLE
koepi: freifunk renovation

### ISSUE THREAD

**Issue by freifunkoperator** [freifunk-berlin/meta#61]
**Contact:**
#koepi:matrix.riotcat.org

**Location:**
The hardware is for the Køpi. The aim is to establish directional radio links to Kreuzberg and Mitte and provide public spaces with connectivity.

**Use:**
The Køpi is a long-standing housing project with open event spaces. The residents allow us to install various directional radio links from the roof. It aims to connect to the Simeon and the Emma. Additionally, the courtyard and the aquarium should be provided with Wi-Fi reception.

**Devices List:**

- Ubiquiti UniFi Switch Flex (ca. 110€)
- Zyxel NWA55AXE (ca. 100€)
- 2 Outdoorkabel (1 Box ca. 140€)
- TL-POE160S (ca. 24€)
- 2 x Ubiquiti Instant PoE 802.3af Gigabit (ca. 25€)

**Total cost:**
Without outdoor cable: 284€

**Comment by noxilixon** [comment]
This request is now older than two months. There are no upvotes right now. I will close this. .... Feel free to make another request 😁

**Comment by noxilixon** [comment]
After a consultation, the issue will be reopened and released for voting with more advertising.
