### ISSUE TITLE
flughafen: maintenance

### ISSUE THREAD

**Issue by FFHener** [freifunk-berlin/meta#63]
- [x] align flughafen-ak36
- [x] align flughafen-rhxb
- [x] flughafen-feld tends to fall to a 100 MBit ethernet connection. The cable must be checked and / or replaced
- [x] flughafen-zoll tends to fall to a 100 MBit ethernet connection. The cable must be checked and / or replaced
- [x] take lora antenna for firmware updates & later reinstall

**Comment by noxilixon** [comment]
I contacted the tenant service and asked for a date.
