### ISSUE TITLE
Hackday 2024-04-21

### ISSUE THREAD

**Issue by ZuquetuPlexis** [freifunk-berlin/meta#65]
[Pad for Organizing](https://pad.freifunk.net/p/FreifunkHackdayBerlin2024)
To organize the upcomming Community Day (21.04.2024) we would need a new pad to write down topics, possible discussions etc.

~~@FFHener You mentioned you could create a new pad for this event?~~

**Comment by FFHener** [comment]
Here is a empty pad: https://pad.freifunk.net/p/FreifunkHackdayBerlin2024
