### ISSUE TITLE
SSDs for a36-hyp03

### ISSUE THREAD

**Issue by nicolasberens** [freifunk-berlin/meta#71]
**Contact:**
Me

**Location:**
alboinkontor, hyp03

**Use:**
Replacement for HDDs
Since we are hosting 11 VMs on spinning rust, the performance is quite underwhelming.
Migrating IO Intensive Workloads to SSDs would increase the user experience.
This would mainly  affect the config wizard, monitor host, buildbot and UISP.

Sata SSDs are chosen because the host does not have NVME Slots, and the only Space for a PCIe Card is taken by the 10GBe network card.

Adapters are needed due to the case having 4x3,5" HDD cages

Space usage:
- Config: 20GB
- Monitor: 200GB
- Buildbot: 1,5TB (but this needs to be rethought)
- UISP: 100G

**Devices List:**
2x 2,5" to 3,5" Adapter: https://www.amazon.de/dp/B00UN550AC/
2x 2TB Enterprise SSD: 
Since prices vary by quite a bit, depending on the price at the moment the prefered options would be:

- https://geizhals.de/samsung-enterprise-ssd-pm893-1-92tb-mz-7l31t900-a2915837.html
- https://geizhals.de/intel-ssd-d3-s4520-1-92tb-ssdsc2kb019tz01-a2620716.html
- https://geizhals.de/micron-5400-pro-read-intensive-1-92tb-mtfddak1t9tga-1bc1zabyy-a2807784.html

If we want to replace All harddrives we would need 4TB SSDs.
Which would add ~300€

**Total cost:**
~600€ 2TB Solution 
~900€ 4TB Solution

**Comment by Noki** [comment]
Wouldn't it be better to look directly at the used market for a replacement for the entire system? The idea of installing new SSDs into 10-year-old hardware is repulsive to me. Maybe we should just write down what our requirements for a new system would be and place a search in "Kleinanzeigen" because maybe someone will sponsor us more modern hardware for a good cause, into which we can then install NVMe disks.

**Comment by nicolasberens** [comment]
Sorry for the late reply, your comment slipped my notifications.

Used Systems usually don't support NVME SSDs. (Or only 1-2 on-board ones without hot-swapping). So we would still rely on SATA ones.

A new System would cost ~4k.

While a newer system might be better, the only constraint we currently have is IO

**Comment by nicolasberens** [comment]
we are going to use a set of existing SSDS.

I bought the fitting adapters.


strategy would be:
- pre mount SSDs and create the partition at home (+ formware upgrade if needed)
- remove one HDD from the vm-raid and add SSD
- `mdadm --manage /dev/md2 --remove /dev/sdc1 `
- `mdadm --manage /dev/md2 --add /dev/sdc1`
- wait until raid is in sync again
- repeat with second disk

**Comment by nicolasberens** [comment]
/dev/sda1 replaced

**Comment by nicolasberens** [comment]
Second drive replaced
