### ISSUE TITLE
zwingli: Wave AP Micro for zwingli  -  emma/agym/gub37

### ISSUE THREAD

**Issue by robertfoss** [freifunk-berlin/meta#79]
**Contact:**
robertfoss

**Location:**
zwingli west window, replacing the current af60lr which can then be moved to emma.

**Use:**
To better connect zwingli to the backbone and make it a much faster node in the network.

This will also make much more efficient use of the few windows at zwingli, by avoiding the zwingli-agym PTP link.

Eventually this AP would be able to provide fast connections for emma, agym & gub37.
![image](https://github.com/freifunk-berlin/meta/assets/523260/23410ed7-fff5-4261-a556-1427f8ed2603)

**Devices List:**
508-535 Eur

https://www.getic.com/product/wave-access-point-micro

https://www.omg.de/richtfunk/60-ghz/ubiquiti-uisp-wave-access-point-micro-wave-ap-micro/a-27836

https://eu.store.ui.com/eu/en/collections/uisp-60ghz-basestation-wide-coverage/products/wave-a-p-micro

**Total cost:**
_Accumulated by current purchase price_
591.01 Eur

(See [instructions](https://github.com/freifunk-berlin/meta/blob/main/Hardware-orders.md))

**Comment by Noki** [comment]
I think this is a really good placement and addition to the network as it provides a second gigabit path to an uplink for both zwingli and emma with only one new device!
