### ISSUE TITLE
Hardwareanfrage ILR-core @ TU Berlin

### ISSUE THREAD

**Issue by Akira25** [freifunk-berlin/meta#80]
**Contact:**
[akira25](https://github.com/Akira25) / Martin Hübner ([Matrix](@akira25:matrix.org))

**Location:**
Technische Universität Berlin, Insitut für Luft- und Raumfahrt ("F-Gebäude"), auf dem Dach der Satelliten-Bodenstation.
https://www.openstreetmap.org/?mlat=52.51514&mlon=13.32364#map=19/52.51514/13.32364&layers=N

**Use:**
Der Standort ist ein Ersatz-Standort für das Hauptgebäude der TU Berlin, welches von 2015 bis ca 2019 Teil des Backbones war. Hauptsächlich soll der Standort als weitere, breitbandige Backbone-Anbindung für den Teufelsberg dienen. In einem Experiment im 3 Quartal 2023 konnten wir mit den 60GHz-Airfibers mit bloßer Sicht-Ausrichtung einen Nettodurchsatz von rund 900MBit/s erzielen.

Vom ILR aus sind die Perleberger36 und der Teufelsberg erreichbar. Das Gateway Stromstraße liegt auch erreichbar, wurde aber wegen der Situation dort vor Ort erstmal nicht berücksichtigt. Perspektivisch ist die Erschließung anderer TU-Gebäude, wie z.B. die Marchstraße (Informatik-Fachschaft: Freitagsrunde) oder das EN-Gebäude (z.B. Loetlabor) möglich.

Der Standort auf dem ILR soll eine Keimzelle für Freifunk im universitären Umfeld sein und durch eine sehr saubere und ordentliche Installation als Türöffner für das Hauptgebäude dienen. Teile des Amateurfunkclubs DK0TU, sowie die Freifunk-AG der TU Berlin sollen am Aufbau beteiligt werden.

**Devices List:**
- [x] Airfiber 60 Richtung Teufelsberg (reserviert)
- [x] USW Flex (reserviert)
- [x] TP-Link POE-Injector (reserviert)
- [x] Rocket mit RF-Elements-Dish Richtung Perleberger (bereits vorhanden)
- [x] 1,50m hoher Mast mit Standfuß, Richtung Teufelsberg (in Kirchofstraße vorhanden)
- [x] 16 Betonplatten für den Standfuß 
- [x] 1,50m hoher Mast mit Standfuß, Richtung Perleberger (vorhanden, bei Perry)

UV-Beständige Kabel (insgesamt ca. 30€):
- [x] POE aus Ground-Station -> Dach: 10 m
- [x] Teufelsberg-Schüssel -> Core-Router: 12,5m
- [x] Perleberger-Schüssel -> Core-Router: 1 m

Es ist angedacht, die Kabel in einem Flexrohr zu verlegen:
- [x] 25m Flexrohr UV Beständig

**Total cost:**
Durch das Einbringen vorhandener Geräte und Masten, fallen geringere Kosten an:

- 51.55€ Kabel
- 33,32€ Flexrohre
- 56€ 16 x Betonplatten (50 x 50)

Gesamt: 140.87€

Bei Einberechnung der bereits beschafften und reservierten Geräte kommen hinzu:

- 340,51€ Airfiber 60
- 105,03€ USW-Flex
- ca 60€ TP-Link POE-Adapter

Gesamt mit vorhandenen Geräten: 646.41€

**Comment by Akira25** [comment]
Edit: Statt der Rohre Klemmschellen und Haltesteine sollen Wellrohre verwendet werden (UV-Bestädnig). Ich konnte gerade noch keinen konkreten Liferanten ausmachen, aber der preis scheint geringer zu sein, wenn man nur dieses verwendet, statt der Klemmrohre und Haltesteine.

**Comment by booo** [comment]
> Edit: Statt der Rohre Klemmschellen und Haltesteine sollen Wellrohre verwendet werden (UV-Bestädnig). Ich konnte gerade noch keinen konkreten Liferanten ausmachen, aber der preis scheint geringer zu sein, wenn man nur dieses verwendet, statt der Klemmrohre und Haltesteine.

Ich glaube am Alexanderplatz sind noch 50m Wellrohr und ggf. auch passende Klemmen. Vielleicht schaust du nochmal dort. Ich kann auch bei Gelegenheit mal schauen.

Vielfach verwendetes Material wurde auch mal unter https://wiki.freifunk.net/Material gesammelt.

**Comment by booo** [comment]
Bekommen wir einen Uplink zu einem Satelliten?

**Comment by Akira25** [comment]
> Bekommen wir einen Uplink zu einem Satelliten?

Leider eher unwahrscheinlich. Aber falls gewünscht, kann ich bei meinem Chef mal eine Führung organisieren. Da kann man sich die Bodenstationstechnik und wie man satelliten baut mal anschauen. :)
