### ISSUE TITLE
Kotti-Core wiederbeleben

### ISSUE THREAD

**Issue by xa-y-ax** [freifunk-berlin/meta#86]
**Contact:**
ff@xayax.de

**Location:**
Kotti - über den Bars
https://wiki.freifunk.net/Berlin:Standorte:Kotti

**Use:**
Ausleuchtung des nördlichen Kottis. Ich denke, man kann die Sektorantenne weiter nutzen. Sie ist für 2 Ghz ausgelegt. Aber wir hatten damals auch guten Empfang mit 5 Ghz auf dem Platz. 

**Devices List:**
- Uplink zur Emmaus-Kirche: entweder Litebeam AC (65 Euro) oder Mikrotik Cube (150 Euro) oder Ubiquiti Wave Nano (300 Euro) ist abhängig davon, was Simon auf der Kirche bauen will bzw. ob der Cube dort bleibt und ptmp kann
- Core mit Antennenausgang (Ubiquiti UniFi Swiss Army Knife Ultra Access Point ca. 80 Euro)
- Patchkabel (ca. 10 Euro)
- Pigtails (ca. 15 Euro)

**Total cost:**
ca. 180 bis 400 Euro - je nach Uplink-Lösung

(See [instructions](https://github.com/freifunk-berlin/meta/blob/main/Hardware-orders.md))

**Comment by Noki** [comment]
Vielleicht wäre ein Miktotik mANTBox auch eine gute Lösung. Eine solche könnte gleichzeitig Core-Router sein und die bisherige Sektorantenne ersetzen.

**Comment by xa-y-ax** [comment]
Ich habe die Hoffnung, dass wir die große Umfeldversorgungs-Sektor weiter nutzen können. Die hatte echt ne gute Abdeckung. Nur der TP3600 war etwas „schwächlich“. Wir könnten auch einen zyxel nehmen. Aber der hat halt diesen Load-bug. Und wir hatten die NSM5 mit POE passtrough konfiguriert um den tp zu versorgen. Wir haben nur 1 Kabel. Dafür brauchen wir also auch noch eine Lösung.

**Comment by Noki** [comment]
Ich habe bei einem reinen 2 GHz Sektor die Befürchtung, dass es das Radio killen könnte, wenn zuviel Energie zurück ins Radio reflektiert wird, da die Stehwelle der 2 GHz Antenne bei 5 GHz nicht passt.

Mit einer Nanobeam 5AC könnte genau das PoE Passthrough weiter genutzt werden, da diese auch 2 Ports hat.

**Comment by kls0e** [comment]
rückseits könnten wir auch das Zentrum Kreuzberg-Hochhaus mit einem nach oben gewinkelten Sektor gut versorgen!

**Comment by xa-y-ax** [comment]
Danke für's Erinnern. Von mir aus können wir das gerne so machen. Eventuell können wir auch die alte NSM5 weiter nutzen als Client sollte die auch mit den AC Dingern auf der Kirche reden können - oder ist das unsinnig das alte Ding weiter zu verwenden?

**Comment by xa-y-ax** [comment]
Wir müssen das "Ubiquiti UniFi Swiss Army Knife" leider ersetzen. Die Bar hat den POE-Injector unzugänglich eingebaut, so dass wir mit 24V klarkommen müssen. 
Erst dachte ich, wir könnten vielleicht eine Rocket vom Feld weiterverwenden - die melden sich aber nicht zurück. Daher - können wir vielleicht nochmal eine 
https://eu.store.ui.com/eu/en/collections/unifi-wifi-outdoor-long-range/products/uap-ac-mesh anschaffen? Kosten ca. 80-90 Euro? 
Das "Ubiquiti UniFi Swiss Army Knife" würde dann frei werden für einen anderen Standort.

**Comment by noxilixon** [comment]
Am Ende haben wir eine `NanoBeam 5AC` verwendet und ein `Unifi ac-mesh`.
