### ISSUE TITLE
ip-assignment: add more ips

### ISSUE THREAD

**Issue by Noki** [freifunk-berlin/meta#87]
We ran out of IPs and currently it is not possible to register new ones. We need to add another IP block.

To keep compatibility with ICVPN we should register a new block via the github.

- https://github.com/freifunk/icvpn-meta
- https://github.com/freifunk/icvpn
- https://wiki.freifunk.net/IP-Netze/IC-VPN

**Comment by Noki** [comment]
from looking at the wiki page there might be some free blocks (10.49, 10.68, 10.70, ... )

**Comment by pmelange** [comment]
We already have more addresses

https://github.com/freifunk/icvpn-meta/pull/623

**Comment by pktpls** [comment]
10.248.0.0/14 is now open for registrations at config.berlin.freifunk.net
