### ISSUE TITLE
Community Day 22.09.2024

### ISSUE THREAD

**Issue by ZuquetuPlexis** [freifunk-berlin/meta#92]
# Proposal Community Day Q3 2024

It's been some time since the last **Community Day**. I want to propose we schedule the next meetup in 08.2024, roughly 6 month after the last one in february.

I'm reusing the [Orga-Pad](https://pad.freifunk.net/p/FreifunkHackdayBerlin2024) from last time.

**Comment by noxilixon** [comment]
Siehe Protokoll Community-Tag [22.9.24](https://github.com/freifunk-berlin/meta/blob/main/protokolle/2024-09-22.md)
