### ISSUE TITLE
Hackday 01.12.2024

### ISSUE THREAD

**Issue by ZuquetuPlexis** [freifunk-berlin/meta#93]
# Proposal Hackday Q4 2024

The next hackday will be at the 1st of Dezember.

ToDos:
- [x] Write a Save the Date
- [x] Book a Room
- [ ] Organize food
- [x] Shedule the event
- [x] Write a invitation
- [ ] Prepare the room

You can add TOPs in the [Orga-Pad](https://pad.freifunk.net/p/FreifunkHackdayBerlin2024).

**Comment by noxilixon** [comment]
Since the last Community-Day was just now, I would propose the hackday to be in the beginning of December.
