### ISSUE TITLE
[Hardware Request] Philmel Nearfield Additions

### ISSUE THREAD

**Issue by Petrella** [freifunk-berlin/meta#99]
**Contact:**
@roedel

**Location:**
Phillip Melanchton Kirche
- Church tower north window
- Church tower west window

**Use:**
The nearfield additions should be used to provide freifunk to the streets surrounding the tower. In addition to already existing nearfield devices in east and west window (Mikrotik Sxtsq5ac) we want to add two more in west and north window to also cover this directions with freifunk. The west Radio/Sxtsq5AC for example covers whole Kranoldplatz with Freifunk.

**Devices List:**
- 2 x SXTsq 5 ac (https://mikrotik.com/product/sxtsq_5_ac)
- 2 x Mount for SXTsq 5 ac (https://www.cyberteam.pl/en/produkt/4870_anti-noise-shield-mikrotik-routerboard-sxtsq-lite5-rbsxtsq5nd-5ghz-16dbi-ptp-cpe)
- 4 x RJ45 Crimp Connectors (already covered)
- Ubi Tough Cable (already covered)

**Total cost:**
150€

(See [instructions](https://github.com/freifunk-berlin/meta/blob/main/Hardware-orders.md))

**Comment by noxilixon** [comment]
@Petrella still two approvals required. Only one week remaining. See instructions: https://github.com/freifunk-berlin/meta/blob/main/Hardware-orders.md#decision

**Comment by noxilixon** [comment]
Closed because of missing community approval. Feel free to try it again.
